import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import {ClerkProvider} from "@clerk/nextjs"
import AppProvider from "@/components/providers/AppProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider afterSignOutUrl={"/sign-in"}
    appearance={{elements:{
      formButtonPrimary:"bg-primary hover:bg-primary/90 text-sm !shadow-none"
    },
    }}>
      <html lang="en" suppressHydrationWarning>
      <body className="__variable_d65c78 antialiased" cz-shortcut-listen="true" screen_capture_injected="true">
        <AppProvider>
          <ThemeProvider>
        {children}
      </ThemeProvider>
        </AppProvider>
      </body>
    </html>
    </ClerkProvider>
  );
}